#!/bin/bash

#simple info gathering script    <3     .0. sudo_KING

#change log: Version 0.6 added RitX (Reverse DNS-IP lookup)
#change log: Version 0.7 added a parsing feature called CHECKitBITCH for the output of SCANitBITCH (scannedBITCH.txt)


BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'              # No Color

echo ""
echo -e "$BLUE                      --=Simple Info Gathering Script=--
                 "
echo    "               Called:"
echo -e $LIGHTCYAN'            (                   )             (                   )  '
echo -e '            )\ )  (    (     ( /(       )  (  )\ )  *   )  (   ( /(  '
echo -e '           (()/(  )\   )\    )\())(  ( /(( )\(()/(` )  /(  )\  )\()) '
echo -e '            /(_)|((_|(((_)( ((_)\ )\ )\())((_)/(_))( )(_)|((_)((_)\  '
echo -e '           (_)) )\___)\ _ )\ _((_|(_|_))((_)_(_)) (_(_()))\___ _((_) '
echo -e '           / __((/ __(_)_\(_) \| |(_) |_ | _ )_ _||_   _((/ __| || | '
echo -e '           \__ \| (__ / _ \ | .` || |  _|| _ \| |   | |  | (__| __ | '
echo -e '           |___/ \___/_/ \_\|_|\_||_|\__||___/___|  |_|   \___|_||_| V0.7'

echo ""
echo -e "$LIGHTGREEN All information found will be saved to: $RED 'scannedBITCH.txt'$GREEN"
echo -e "                   $LIGHTBLUE Brought To You BY:" "$YELLOW .0. sudo_KING"
echo ""
echo -e $YELLOW"NOTE:$BLUE
This script requires$RED 'nmap'$BLUE, $RED'RitX (/tools/ritx/RitX.pl)'$BLUE and $RED'nikto (/usr/bin/nikto)'$BLUE installed to work properly."
echo ""
echo -e "$RED Disclaimer:\n $GREEN
Any actions and or activities related to the material contained within this Script are solely your responsibility.
The misuse of this Script can result in criminal charges brought against the person/s in question.
The author will not be held responsible in the event any criminal charges be brought against any individuals misusing the Script to break the law."$NC
echo ""
read -p "Do you accept these terms? <Y/N> " prompt
echo ""
if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]
then
  read -p " Input Target IP and hit enter: " text
else
  exit 0
fi
echo ""
echo -e "                      $LIGHTGREEN Happy Hunting!!"$NC
sleep 4
echo ""

echo -e "$RED Checking if Target is 'ping'able:"$NC
sleep 2
ping -w 5 $text| tee -a scannedBITCH.txt
sleep 3
echo ""

echo -e "$RED Gathering information on 'host' Target:"$NC
sleep 2
host $text | tee -a scannedBITCH.txt
sleep 3
echo ""

echo -e "$RED Gathering 'nslookup' on 'host' Target:"$NC
sleep 2
nslookup $text | tee -a scannedBITCH.txt
sleep 3
echo ""

echo -e "$RED Gathering 'dig' info on 'host' Target:"$NC
sleep 2
dig $text | tee -a scannedBITCH.txt
sleep 3
echo ""

echo -e "$RED Gathering 'whois' on Target:"$NC
sleep 2
whois $text | tee -a scannedBITCH.txt
sleep 3
echo ""

echo -e "$RED Finding path from you to Target:"$NC
sleep 2
traceroute $text| tee -a scannedBITCH.txt
sleep 3
echo ""

echo -e "$RED Beginning 'RitX' (Reverse-DNS/IP Lookup) scan... \n $LIGHTCYAN Stand By!"$NC
sleep 2
/tools/ritx/RitX.pl -t $text | tee -a scannedBITCH.txt
sleep 3
echo ""

echo -e "$RED Beginning nmap (Network Mapping) scan... \n $LIGHTCYAN Be patient young grasshopper!"$NC
sleep 2
sudo nmap -sS -T2 -oG /opt/tools/SCANitBITCH/tmp/nmapBITCH.out -A -O -sV -sC -PN --script=/opt/tools/vulscan/vulscan$

sleep 3
echo ""

echo -e "$RED Beginning 'nikto' (Looking for Webserver and vulns) scan... \n $LIGHTCYAN HOLD ON TO YOUR ASS!"$NC
sleep 2
/usr/bin/nikto @@ALL -host $text | tee -a scannedBITCH.txt
sleep 3
echo ""

echo -e "$LIGHTBLUE This scan is now finished.$RED For a detailed output please see: ~/'scannedBITCH.txt'"
sleep 2
echo ""
read -p "Do you want to run CHECKitBITCH? (This parses your output for you): " prompt
echo ""
if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]
then

#CHECKiTBITCH
Out='scannedBITCH.txt'

echo -e "We are now going to look for some 'Interesting Findings'"
echo -e "Sit the$RED FU(K$NC down, pull out a$GREEN Bong$NC and relax..."
echo -e "We'll let you know when it's done, or if anything is note worthy!"
echo ""
sleep 3;

echo -e "$RED Is it Alive?:" $NC ;
grep 'ping statistics' $Out
grep 'packets transmitted*' $Out
sleep 2;
echo ""

echo -e "$RED Lets see who this MoFo is:" $NC ;
grep 'OrgName' $Out
grep 'Address' $Out
grep 'City' $Out
grep 'StateProv' $Out
grep 'Country' $Out
sleep 2;
echo ""

echo -e "$RED What open ports and services is this MoFo running?:" $NC ;
grep -i open /opt/tools/SCANitBITCH/tmp/nmapBITCH.out
echo ""
sleep 2;

read -p "Do you want to clean up the Nmap Scan output from your machine? " prompt
echo ""
if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]
then
rm /opt/tools/SCANitBITCH/tmp/nmapBITCH.out 
echo -e "$RED Cleaned up output from nmap" $NC ;
else
echo -e "$RED Nothing was deleted! You dirty boy you!" $NC ;
fi
sleep 3;
echo -e "$RED What possible ins do I have?:" $NC ;
grep '+' $Out
sleep 2;
echo ""
echo -e "$RED Take a$YELLOW L00K$RED:" $NC ;
#grep further work in progress (WIP)  
else
echo ""
echo -e "$RED Nothing was done, check the normal output (scannedBITCH.txt)" $NC ;
fi
sleep 3;

#eof
